name: CI Smoke
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker (Windows)
        uses: crazy-max/ghaction-setup-docker@v3

      - name: Docker version
        shell: pwsh
        run: docker version

      - name: Compose up (planner+gwfwd)
        shell: pwsh
        run: >
          docker compose
          -f docker-compose.yml
          -f docker-compose.gwfwd.yml
          -f docker-compose.runtime.yml
          up -d --build

      - name: Wait health 19090
        shell: pwsh
        run: |
          $u='http://localhost:19090/health'
          for($i=0;$i -lt 60;$i++){ if((curl.exe -s -o NUL -w '%{http_code}' $u) -eq '200'){exit 0}; Start-Sleep -Seconds 1 }
          throw 'health 19090 timeout'

      - name: Wait health 38888
        shell: pwsh
        run: |
          $u='http://localhost:38888/health'
          for($i=0;$i -lt 60;$i++){ if((curl.exe -s -o NUL -w '%{http_code}' $u) -eq '200'){exit 0}; Start-Sleep -Seconds 1 }
          throw 'health 38888 timeout'

      - name: CI Smoke (PowerShell)
        shell: pwsh
        run: .\scripts\ci_smoke_gwfwd.ps1

      - name: CI Smoke (CMD)
        shell: cmd
        run: .\scripts\ci_smoke_gwfwd.cmd

      - name: Compose logs (on fail)
        if: failure()
        shell: pwsh
        run: |
          docker compose -f docker-compose.yml -f docker-compose.gwfwd.yml -f docker-compose.runtime.yml ps
          docker compose -f docker-compose.yml -f docker-compose.gwfwd.yml -f docker-compose.runtime.yml logs --no-color

      - name: Compose down
        if: always()
        shell: pwsh
        run: docker compose -f docker-compose.yml -f docker-compose.gwfwd.yml -f docker-compose.runtime.yml down -v
