name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker compose version

      - name: Build and start
        run: docker compose up -d --build planner gateway

      - name: Wait for gateway
        run: |
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:18088/health || true)
            if [ "$code" = "200" ]; then exit 0; fi
            sleep 2
          done
          echo "gateway health not 200"
          docker compose logs gateway planner
          exit 1

      - name: E2E
        run: |
          plan=$(curl -s -H 'Content-Type: application/json' -d '{}' http://localhost:18088/v1/plan/compile | python3 -c "import sys,json; print(json.load(sys.stdin)['planId'])")
          [ -n "$plan" ] || { echo "no planId"; exit 1; }
          code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:18088/v1/plan/$plan)
          [ "$code" = "200" ] || { echo "get $code"; exit 1; }

      - name: Teardown
        if: always()
        run: docker compose down -v
