name: ci

on:
  push:
    branches: [ "**" ]
    tags:     [ "v*", "V*" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: docker compose build

      - name: Up services
        run: docker compose up -d

      - name: Wait health (planner+gateway)
        run: |
          for i in {1..60}; do
            p=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:19090/health || true)
            g=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:18088/health || true)
            if [ "$p" = "200" ] && [ "$g" = "200" ]; then echo "OK"; exit 0; fi
            sleep 2
          done
          echo "Health timeout"
          docker compose logs --tail=200
          exit 1

      - name: E2E smoke (200→410)
        shell: pwsh
        run: ./scripts/e2e_smoke.ps1 -Base "http://localhost:18088" -PollSeconds 5 -DeadlineSeconds 180

      - name: Teardown
        if: always()
        run: docker compose down -v

  publish:
    needs: build-test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PLANNER_IMAGE: ghcr.io/${{ github.repository_owner }}/gw-stack-planner
      GATEWAY_IMAGE: ghcr.io/${{ github.repository_owner }}/gw-stack-gateway
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta (planner)
        id: meta_planner
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PLANNER_IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha

      - name: Meta (gateway)
        id: meta_gateway
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GATEWAY_IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha

      - name: Build+Push planner
        uses: docker/build-push-action@v6
        with:
          context: ./planner
          push: true
          tags: ${{ steps.meta_planner.outputs.tags }}
          labels: ${{ steps.meta_planner.outputs.labels }}
          build-args: |
            GW_VERSION=${{ github.ref_name }}
            GW_COMMIT=${{ github.sha }}

      - name: Build+Push gateway
        uses: docker/build-push-action@v6
        with:
          context: ./gateway
          push: true
          tags: ${{ steps.meta_gateway.outputs.tags }}
          labels: ${{ steps.meta_gateway.outputs.labels }}
          build-args: |
            GW_VERSION=${{ github.ref_name }}
            GW_COMMIT=${{ github.sha }}
