name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose build

      - name: Start stack
        run: docker compose up -d

      - name: Wait for services
        run: |
          for i in {1..20}; do
            curl -fsS http://localhost:18088/health && break || sleep 3
          done
          curl -fsS http://localhost:19090/health

      - name: UI smoke
        run: curl -fsS http://localhost:18088/

      - name: API smoke via gateway
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          PLANID=$(curl -fsS -X POST http://localhost:18088/v1/plan/compile | jq -r .planId)
          test ${#PLANID} -eq 36
          curl -fsS "http://localhost:18088/v1/plan/$PLANID"

      - name: Show logs on failure
        if: ${{ failure() }}
        run: docker compose logs --no-color

      - name: Teardown
        if: always()
        run: docker compose down -v
