name: gw-ci
on: [push, workflow_dispatch]
jobs:
  ttl410:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: start stack
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build
      - name: wait health
        run: |
          for i in {1..60}; do
            curl -fsS http://localhost:18088/health >/dev/null && curl -fsS http://localhost:19090/health >/dev/null && exit 0
            sleep 2
          done
          exit 1
      - name: compile
        run: |
          PLANID=$(curl -fsS -X POST http://localhost:18088/v1/plan/compile -H "Content-Type: application/json" -d '{}' | jq -r .planId)
          echo "PLANID=$PLANID" >> $GITHUB_ENV
      - name: assert 200
        run: |
          curl -fsS -o resp.json -w "%{http_code}\n" http://localhost:18088/v1/plan/$PLANID | tee code.txt | grep -q '^200$'
      - name: wait ttl
        run: sleep 70
      - name: assert 410
        run: |
          curl -fsS -o resp_ttl.json -w "%{http_code}\n" http://localhost:18088/v1/plan/$PLANID | tee code_ttl.txt | grep -q '^410$'
      - name: lint nginx
        run: docker exec $(docker ps -qf "name=gateway") nginx -t
      - name: artefacts
        run: |
          mkdir -p artefacts
          docker compose logs gateway > artefacts/gateway.log
          docker compose logs planner > artefacts/planner.log
          printf "PORT=18088 | HEALTH=200 | PLANID=%s | GET=200/410 | SUMMARY=PASS\n" "$PLANID" > artefacts/report.txt
      - uses: actions/upload-artifact@v4
        with:
          name: gw-artefacts
          path: artefacts
