name: gw-ci
on: [push, workflow_dispatch]
jobs:
  ttl410:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check docker
        run: |
          docker --version
          if ! docker compose version; then
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
            docker compose version
          fi
      - name: deps
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: start stack
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build
          docker compose ps
      - name: wait health
        run: |
          for i in {1..90}; do
            curl -fsS http://localhost:18088/health >/dev/null && curl -fsS http://localhost:19090/health >/dev/null && exit 0
            sleep 2
          done
          docker compose ps
          exit 1
      - name: compile
        run: |
          PLANID=$(curl -fsS -X POST http://localhost:18088/v1/plan/compile -H "Content-Type: application/json" -d '{}' | jq -r .planId)
          echo "PLANID=$PLANID" >> $GITHUB_ENV
      - name: assert 200
        run: |
          curl -fsS -o resp.json -w "%{http_code}\n" http://localhost:18088/v1/plan/$PLANID | tee code.txt | grep -q '^200$'
      - name: wait ttl
        run: sleep 70
      - name: assert 410
        run: |
          curl -fsS -o resp_ttl.json -w "%{http_code}\n" http://localhost:18088/v1/plan/$PLANID | tee code_ttl.txt | grep -q '^410$'
      - name: lint nginx
        run: docker exec $(docker ps -qf "name=gateway") nginx -t
      - name: collect logs
        if: always()
        run: |
          mkdir -p artefacts
          docker compose ps > artefacts/compose.ps.txt || true
          docker ps -a > artefacts/docker.ps-a.txt || true
          docker compose logs --no-color > artefacts/compose.logs.txt || true
          printf "PORT=18088 | HEALTH=200 | PLANID=%s | GET=200/410 | SUMMARY=PASS\n" "$PLANID" > artefacts/report.txt || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gw-artefacts
          path: artefacts
