name: gw-ci
on: [push, workflow_dispatch]
jobs:
  ttl410:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: start stack
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build
          docker compose ps
      - name: wait health
        run: |
          for i in {1..120}; do
            curl -fsS http://localhost:18088/health >/dev/null && curl -fsS http://localhost:19090/health >/dev/null && exit 0
            sleep 2
          done
          echo "::group::compose ps"; docker compose ps; echo "::endgroup::"
          echo "::group::gateway logs"; docker compose logs gateway | tail -n 200; echo "::endgroup::"
          echo "::group::planner logs"; docker compose logs planner | tail -n 200; echo "::endgroup::"
          exit 1
      - name: compile
        run: |
          PLANID=$(curl -fsS -X POST http://localhost:18088/v1/plan/compile -H "Content-Type: application/json" -d '{}' | jq -r .planId)
          echo "PLANID=$PLANID" >> $GITHUB_ENV
      - name: assert 200
        run: |
          curl -fsS -o resp.json -w "%{http_code}\n" http://localhost:18088/v1/plan/$PLANID | tee code.txt | grep -q '^200$'
      - name: wait ttl
        run: sleep 70
      - name: assert 410
        run: |
          curl -fsS -o resp_ttl.json -w "%{http_code}\n" http://localhost:18088/v1/plan/$PLANID | tee code_ttl.txt | grep -q '^410$'
      - name: summary
        if: always()
        run: |
          {
            echo "## docker compose ps"
            docker compose ps
            echo ""
            echo "## gateway last 80 lines"
            docker compose logs gateway | tail -n 80
            echo ""
            echo "## planner last 80 lines"
            docker compose logs planner | tail -n 80
            echo ""
            echo "## curl health"
            curl -i http://localhost:18088/health || true
            curl -i http://localhost:19090/health || true
          } >> $GITHUB_STEP_SUMMARY
